# Generated by Django 3.1.2 on 2021-01-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20210105_1138'),
        ('orders', '0004_auto_20210105_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_adress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_adress',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='addresses.address'),
        ),
    ]
