# Generated by Django 3.1.2 on 2021-01-23 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectViewd',
            new_name='ObjectViewed',
        ),
    ]
